var exerciseTypes = [
    { name: "One Arm Dumbbell Row", tags: ["back"] },
    { name: "Lat Pulldown Wide", tags: ["back"] },
    { name: "Lat Pulldown Narrow", tags: ["back"] },
    { name: "Cable Row w/ Wide Neutral Grip", tags: ["back"] },
    { name: "Cable Row w/ Neutral Grip", tags: ["back"] },
    { name: "Cable Row w/ Over Grip", tags: ["back"] },
    { name: "Rear Deltoid Machine", tags: ["back"] },
    { name: "Biceps Curl", tags: ["biceps"] },
    { name: "Hammer Curl", tags: ["biceps"] },
    { name: "Military Press", tags: [] },
    { name: "Bench Press", tags: [] },
    { name: "Bench Press Dumbbell", tags: [] },
    { name: "Butterfly", tags: [] },
    { name: "Incline Bench Press", tags: [] },
    { name: "Incline Bench Press Dumbbell", tags: [] },
    { name: "Leg Press", tags: [] },
    { name: "Squat", tags: [] },
    { name: "Leg Curl", tags: [] },
    { name: "Leg Extension", tags: [] },
    { name: "Dips", tags: [] },
    { name: "Under Grip Pull Up", tags: [] },
    { name: "Over Grip Pull Up", tags: [] },
    { name: "Cable Biceps Curl", tags: [] },
    { name: "Supported Biceps Curl", tags: [] },
    { name: "Cable Triceps", tags: [] },
    { name: "Deadlift", tags: [] },
    { name: "Standing Calf Raises", tags: [] },
    { name: "Face Pull", tags: [] },
    { name: "Machine Shoulder Press", tags: [] },
    { name: "Dumbbell Shoulder Press", tags: [] },
    { name: "Machine Bench Press", tags: [] },
    { name: "21s", tags: [] }
];