var exerciseTypes = [
    { name: "One Arm Dumbbell Row", tags: ["back"] },
    { name: "Lat Pulldown Wide", tags: ["back"] },
    { name: "Lat Pulldown Narrow", tags: ["back"] },
    { name: "Cable Row w/ Wide Neutral Grip", tags: ["back"] },
    { name: "Cable Row w/ Neutral Grip", tags: ["back"] },
    { name: "Cable Row w/ Over Grip", tags: ["back"] },
    { name: "Rear Deltoid Machine", tags: ["back"] },
    { name: "Biceps Curl", tags: ["biceps"] },
    { name: "Hammer Curl", tags: ["biceps"] },
    { name: "Military Press", tags: [] },
    { name: "Bench Press", tags: [] },
    { name: "Bench Press Dumbbell", tags: [] },
    { name: "Butterfly", tags: [] },
    /*
    "Incline Bench Press",
    "Incline Bench Press Dumbbell",
    "Leg Press",
    "Squat",
    "Leg Curl",
    "Leg Extension",
    "Dips",
    "Under Grip Pull Up",
    "Over Grip Pull Up",
    "Cable Biceps Curl",
    "Supported Biceps Curl",
    "Cable Triceps",
    "Deadlift",
    "Standing Calf Raises",
    "Face Pull",
    "Machine Shoulder Press",
    "Dumbbell Shoulder Press",
    "Machine Bench Press",
    "21s"
    */
];